name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  exit_if_draft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - name: Do not run on draft PRs
        run: exit 0
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Verify
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
